phase03make: avicente_tsort.c avicente_tsort_helpers.c
	gcc -O3 -o tsort avicente_tsort_helpers.c avicente_tsort.c -pthread

phase02make: avicente_tsort_phase02.c avicente_tsort_helpers_phase02.c
	gcc -O3 -o tsort avicente_tsort_helpers_phase02.c avicente_tsort_phase02.c -pthread
